# Generated by Django 4.1.7 on 2023-05-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rreg", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receiverlist",
            name="organ",
        ),
        migrations.AddField(
            model_name="receiverlist",
            name="organ_needed",
            field=models.CharField(
                blank=True,
                choices=[
                    ("select", "Select needed organ"),
                    ("kidney", "Kidney"),
                    ("lung", "Lung"),
                    ("liver", "Liver"),
                    ("pancreas", "Pancreas"),
                    ("intestine", "Intestine"),
                    ("eye", "Eye"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
