# Generated by Django 4.1.7 on 2023-06-05 00:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rreg", "0005_receiverlist_user_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receiverlist",
            name="user_name",
        ),
    ]
