# Generated by Django 4.1.7 on 2023-06-02 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dreg", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonorList",
            fields=[
                (
                    "donorlist_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="dreg.donorlist",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(blank=True, max_length=30, null=True)),
                ("last_name", models.CharField(blank=True, max_length=30, null=True)),
            ],
            bases=("dreg.donorlist",),
        ),
    ]
