# Generated by Django 4.1.7 on 2023-06-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_remove_homepagebody_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagebody",
            name="title",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
