# Generated by Django 4.1.7 on 2023-05-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DonorList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female")],
                        max_length=6,
                        null=True,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                (
                    "organ",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("empty", "Select organ"),
                            ("kidney", "Kidney"),
                            ("lung", "Lung"),
                            ("liver", "Liver"),
                            ("pancreas", "Pancreas"),
                            ("intestine", "Intestine"),
                            ("eye", "Eye"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("a+", "A+"),
                            ("a-", "A-"),
                            ("b+", "B+"),
                            ("b-", "B-"),
                            ("o+", "O+"),
                            ("o-", "O-"),
                            ("ab+", "AB+"),
                            ("ab-", "AB-"),
                        ],
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "emergency_contact_number",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "choose_identity_card",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pancard", "Pancard"),
                            ("adhaarcard", "Aadhaarcard"),
                            ("voterid", "Voterid"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "enter_identity_card_number",
                    models.IntegerField(blank=True, null=True),
                ),
                ("phone_number", models.IntegerField(blank=True, null=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=10, null=True)),
                ("home_address", models.TextField(blank=True, null=True)),
                (
                    "last_donate_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "any_diseases",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "allergies",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "cardiac",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "bleeding_disorders",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "hbsAg_hcv_hIV",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=4,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
