# Generated by Django 4.1.7 on 2023-05-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dreg", "0002_remove_donorlist_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donorlist",
            name="organ",
            field=models.CharField(
                blank=True,
                choices=[
                    ("all", "All"),
                    ("kidney", "Kidney"),
                    ("lung", "Lung"),
                    ("liver", "Liver"),
                    ("pancreas", "Pancreas"),
                    ("intestine", "Intestine"),
                    ("eye", "Eye"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
