# Generated by Django 4.1.7 on 2023-06-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dreg", "0003_rename_user_donorlist_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donorlist",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
