# Generated by Django 4.1.7 on 2023-06-05 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dreg", "0004_alter_donorlist_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donorlist",
            name="user_name",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donor_lists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
